[[redirects]]
  from = "/github/*"
  to = "https://github.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[build]
  publish = "/opt/build/repo/out"
  command = "pnpm run build"