blank_issues_enabled: true
contact_links:
  - name: Feature request 🚀
    url: https://github.com/successible/document-that/issues/new
    about: Request a new feature
  - name: Bug 🪲
    url: https://github.com/successible/document-that/issues/new
    about: Report a bug
  - name: Chat with us 💬
    url: https://github.com/successible/document-that/discussions
    about: Ask a question or give feedback
